# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [11]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''

a_slice_prev = np.random.randint(10, size=48).reshape(4,4,3)
print("a_slice_prev={}".format(a_slice_prev))
W= np.random.randint(2, size=48).reshape(4,4,3)
print("W={}".format(W))
b= np.random.randint(2, size=1).reshape(1,1,1)
print("b={}".format(b))
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

a_slice_prev=[[[3 8 4]
  [0 1 6]
  [3 3 1]
  [9 1 4]]

 [[4 7 9]
  [6 6 8]
  [2 7 0]
  [3 0 9]]

 [[2 6 1]
  [4 5 0]
  [3 1 1]
  [8 8 7]]

 [[9 6 5]
  [7 3 5]
  [5 3 1]
  [0 2 2]]]
W=[[[0 0 0]
  [0 1 0]
  [0 0 0]
  [1 0 0]]

 [[1 1 1]
  [0 1 1]
  [0 1 0]
  [1 1 1]]

 [[0 1 0]
  [0 1 1]
  [0 0 1]
  [0 1 0]]

 [[1 0 1]
  [1 0 0]
  [0 1 0]
  [0 0 0]]]
b=[[[1]]]
Z = 108.0
