# 作業
### 用 digits (dataset.load_digits()) 資料嘗試跑 t-SNE

In [1]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
from sklearn.manifold import TSNE
import pandas as pd
import seaborn as sns

digits = datasets.load_digits()
X = digits.data
y = digits.target

In [2]:
print(X)
print(X.shape)
print(y)
print(y.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)
[0 1 2 ... 8 9 8]
(1797,)


In [3]:
tsne = manifold.TSNE(n_components=2, random_state=0, init='pca', learning_rate=200., early_exaggeration=12.)
newX = tsne.fit_transform(X)

NameError: name 'manifold' is not defined

In [ ]:
print(newX)
print(newX.shape)

In [ ]:
data= np.concatenate((newX, y.reshape(-1,1)), axis=1)
df = pd.DataFrame(data, columns=["X1", "X2", "y"])
df

In [4]:
plt.figure(figsize=(10,5))
sns.set(style="whitegrid")
sns.scatterplot(data=df, x="X1", y="X2", hue="y", palette="Set1")

AttributeError: module 'seaborn' has no attribute 'scatterplot'

<Figure size 720x360 with 0 Axes>